export const apiCallStatus = {
  API_CALL_START: 'API_CALL_START',
  API_CALL_ERROR: 'API_CALL_ERROR'
};

export const login = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE'
};

export const signUp = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE'
};

export const incidents = {
  GET_ALL_REDFLAGS_SUCCESS: 'GET_ALL_REDFLAGS_SUCCESS',
  GET_ALL_REDFLAGS_FAILURE: 'GET_ALL_REDFLAGS_FAILURE'
};
